# Generated by Django 2.0.4 on 2018-06-04 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20180524_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('private', '仅对自己可见'), ('common', '全部可见'), ('part_visual', '部分可见')], default='private', max_length=20)),
                ('video_url', models.CharField(default='', max_length=200)),
                ('image_url', models.CharField(default='', max_length=200)),
                ('send_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
